export const ADD_TODO = "ADD_TODO"
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS"
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE"

export const TASK_DONE = "TASK_DONE"
export const TASK_DONE_SUCCESS = "TASK_DONE_SUCCESS"
export const TASK_DONE_FAILURE = "TASK_DONE_FAILURE"

export const REMOVE_TASK = "REMOVE_TASK"
export const REMOVE_TASK_SUCCESS = "REMOVE_TASK_SUCCESS"
export const REMOVE_TASK_FAILURE = "REMOVE_TASK_FAILURE"

export const EDIT_TASK = "EDIT_TASK"
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS"
export const EDIT_TASK_FAILURE = "EDIT_TASK_FAILURE"
